// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: "http://217.77.8.234:9600" | (string & {});
};

export type Authorisation = {
  authorisationKey:
    | "CREATE_ROLE"
    | "UPDATE_ROLE"
    | "DELETE_ROLE"
    | "GET_ROLE"
    | "CREATE_USER"
    | "UPDATE_USER"
    | "DELETE_USER"
    | "GET_USER_DETAILS"
    | "UPDATE_PASSWORD"
    | "UPDATE_MY_INFOS"
    | "BLOCK_USER"
    | "UNBLOCK_USER"
    | "ADD_DOCUMENT_TO_USER"
    | "REMOVE_DOCUMENT_TO_USER"
    | "GET_DOCUMENT_OF_USER"
    | "GET_USERS"
    | "CREATE_ADDRESS"
    | "UPDATE_ADDRESS"
    | "DELETE_ADDRESS"
    | "GET_ALL_ADDRESS"
    | "GET_MY_ADDRESS"
    | "CREATE_ADMIN"
    | "UPDATE_ADMIN"
    | "DELETE_ADMIN"
    | "GET_ALL_ADMIN"
    | "GET_ADMIN"
    | "CREATE_SAAS_USER"
    | "UPDATE_SAAS_USER"
    | "DELETE_SAAS_USER"
    | "GET_ALL_SAAS_USERS"
    | "GET_SAAS_USER"
    | "GET_ALL_AUTHORISATIONS"
    | "NOT_SPECIFY"
    | "CREATE_PLAYER"
    | "BLOCK_PLAYER"
    | "UNBLOCK_PLAYER"
    | "ADD_DOCUMENT_TO_PLAYER"
    | "REMOVE_DOCUMENT_TO_PLAYER"
    | "GET_DOCUMENT_OF_PLAYER"
    | "UPDATE_PLAYER"
    | "DELETE_PLAYER"
    | "GET_PLAYER_DETAILS"
    | "GET_PLAYER"
    | "CREATE_SAAS_ADMIN"
    | "BLOCK_SAAS_ADMIN"
    | "UNBLOCK_SAAS_ADMIN"
    | "ADD_DOCUMENT_TO_SAAS_ADMIN"
    | "REMOVE_DOCUMENT_TO_SAAS_ADMIN"
    | "GET_DOCUMENT_OF_SAAS_ADMIN"
    | "UPDATE_SAAS_ADMIN"
    | "DELETE_SAAS_ADMIN"
    | "GET_SAAS_ADMIN_DETAILS"
    | "GET_SAAS_ADMIN";
  authorisationName: string;
  authorisationDescription: string;
  authorisationLevel: string;
  authorisationGroup: AuthorisationGroup;
};

export type AuthorisationGroup = {
  groupCode:
    | "MANAGE_ROLE"
    | "MANAGE_USER"
    | "MANAGE_ADDRESS"
    | "MANAGE_AUTHORISATIONS"
    | "MANAGE_SAAS_USER"
    | "NOT_SPECIFY"
    | "MANAGE_PLAYER"
    | "MANAGE_SAAS_ADMIN";
  groupName: string;
  groupDescription: string;
};

export type Role = {
  roleCode: string;
  roleName: string;
  state: "ACTIVE" | "INACTIVE" | "DELETED" | "CREATE_BUT_NOT_ACTIVE";
  roleDescription: string;
  authorisations: Array<Authorisation>;
  createdBy?: string;
  createdDate: string;
  lastModifiedBy?: string;
  lastModifiedDate: string;
};

export type FileData = {
  id?: number;
  name: string;
  pathData: string;
  extension: string;
  url: string;
};

export type AddressResponseDto = {
  addressCode: string;
  addressCountry: string;
  addressCity: string;
  addressPhoneNumber: string;
  addressEmail: string;
  addressDescription: string;
  state: "ACTIVE" | "INACTIVE" | "DELETED" | "CREATE_BUT_NOT_ACTIVE";
  addressAffiliationDate: string;
  addressPostalCode: string;
  userCode: string;
  addressType: "LOCATION" | "UNKNOWN";
};

export type AuthorisationResponseDto = {
  authorisationKey:
    | "CREATE_ROLE"
    | "UPDATE_ROLE"
    | "DELETE_ROLE"
    | "GET_ROLE"
    | "CREATE_USER"
    | "UPDATE_USER"
    | "DELETE_USER"
    | "GET_USER_DETAILS"
    | "UPDATE_PASSWORD"
    | "UPDATE_MY_INFOS"
    | "BLOCK_USER"
    | "UNBLOCK_USER"
    | "ADD_DOCUMENT_TO_USER"
    | "REMOVE_DOCUMENT_TO_USER"
    | "GET_DOCUMENT_OF_USER"
    | "GET_USERS"
    | "CREATE_ADDRESS"
    | "UPDATE_ADDRESS"
    | "DELETE_ADDRESS"
    | "GET_ALL_ADDRESS"
    | "GET_MY_ADDRESS"
    | "CREATE_ADMIN"
    | "UPDATE_ADMIN"
    | "DELETE_ADMIN"
    | "GET_ALL_ADMIN"
    | "GET_ADMIN"
    | "CREATE_SAAS_USER"
    | "UPDATE_SAAS_USER"
    | "DELETE_SAAS_USER"
    | "GET_ALL_SAAS_USERS"
    | "GET_SAAS_USER"
    | "GET_ALL_AUTHORISATIONS"
    | "NOT_SPECIFY"
    | "CREATE_PLAYER"
    | "BLOCK_PLAYER"
    | "UNBLOCK_PLAYER"
    | "ADD_DOCUMENT_TO_PLAYER"
    | "REMOVE_DOCUMENT_TO_PLAYER"
    | "GET_DOCUMENT_OF_PLAYER"
    | "UPDATE_PLAYER"
    | "DELETE_PLAYER"
    | "GET_PLAYER_DETAILS"
    | "GET_PLAYER"
    | "CREATE_SAAS_ADMIN"
    | "BLOCK_SAAS_ADMIN"
    | "UNBLOCK_SAAS_ADMIN"
    | "ADD_DOCUMENT_TO_SAAS_ADMIN"
    | "REMOVE_DOCUMENT_TO_SAAS_ADMIN"
    | "GET_DOCUMENT_OF_SAAS_ADMIN"
    | "UPDATE_SAAS_ADMIN"
    | "DELETE_SAAS_ADMIN"
    | "GET_SAAS_ADMIN_DETAILS"
    | "GET_SAAS_ADMIN";
  authorisationGroup: AuthorisationGroup;
  authorisationName: string;
  authorisationDescription: string;
};

export type RequestResultUserResponseDto = {
  timestamp: string;
  data?: UserResponseDto;
  code: number;
  status:
    | "SUCCESS"
    | "ERROR"
    | "NOT_ENOUGH_FOUND"
    | "IN_PENDING_STATE"
    | "TIMED_OUT_OR_EXPIRED";
  message?: string;
  details?: {
    [key: string]: unknown;
  };
};

export type RoleResponseDto = {
  roleCode: string;
  roleName: string;
  authorisations: Array<AuthorisationResponseDto>;
  roleDescription: string;
};

export type UserResponseDto = {
  userCode: string;
  userNames: string;
  userPhoneNumber: string;
  userState: "ACTIVE" | "INACTIVE" | "DELETED" | "CREATE_BUT_NOT_ACTIVE";
  roles: Array<RoleResponseDto>;
  token: string;
  preferredCurrency: string;
  userEmail: string;
  addresses: Array<AddressResponseDto>;
  image: string;
};

export type UserCredentialsDto = {
  lastPassword: string;
  newPassword: string;
};

export type RoleRequestDto = {
  roleCode: string;
  roleName: string;
  authorisationsCode: Array<
    | "CREATE_ROLE"
    | "UPDATE_ROLE"
    | "DELETE_ROLE"
    | "GET_ROLE"
    | "CREATE_USER"
    | "UPDATE_USER"
    | "DELETE_USER"
    | "GET_USER_DETAILS"
    | "UPDATE_PASSWORD"
    | "UPDATE_MY_INFOS"
    | "BLOCK_USER"
    | "UNBLOCK_USER"
    | "ADD_DOCUMENT_TO_USER"
    | "REMOVE_DOCUMENT_TO_USER"
    | "GET_DOCUMENT_OF_USER"
    | "GET_USERS"
    | "CREATE_ADDRESS"
    | "UPDATE_ADDRESS"
    | "DELETE_ADDRESS"
    | "GET_ALL_ADDRESS"
    | "GET_MY_ADDRESS"
    | "CREATE_ADMIN"
    | "UPDATE_ADMIN"
    | "DELETE_ADMIN"
    | "GET_ALL_ADMIN"
    | "GET_ADMIN"
    | "CREATE_SAAS_USER"
    | "UPDATE_SAAS_USER"
    | "DELETE_SAAS_USER"
    | "GET_ALL_SAAS_USERS"
    | "GET_SAAS_USER"
    | "GET_ALL_AUTHORISATIONS"
    | "NOT_SPECIFY"
    | "CREATE_PLAYER"
    | "BLOCK_PLAYER"
    | "UNBLOCK_PLAYER"
    | "ADD_DOCUMENT_TO_PLAYER"
    | "REMOVE_DOCUMENT_TO_PLAYER"
    | "GET_DOCUMENT_OF_PLAYER"
    | "UPDATE_PLAYER"
    | "DELETE_PLAYER"
    | "GET_PLAYER_DETAILS"
    | "GET_PLAYER"
    | "CREATE_SAAS_ADMIN"
    | "BLOCK_SAAS_ADMIN"
    | "UNBLOCK_SAAS_ADMIN"
    | "ADD_DOCUMENT_TO_SAAS_ADMIN"
    | "REMOVE_DOCUMENT_TO_SAAS_ADMIN"
    | "GET_DOCUMENT_OF_SAAS_ADMIN"
    | "UPDATE_SAAS_ADMIN"
    | "DELETE_SAAS_ADMIN"
    | "GET_SAAS_ADMIN_DETAILS"
    | "GET_SAAS_ADMIN"
  >;
  roleDescription: string;
  state: "ACTIVE" | "INACTIVE" | "DELETED" | "CREATE_BUT_NOT_ACTIVE";
};

export type RequestResultRoleResponseDto = {
  timestamp: string;
  data?: RoleResponseDto;
  code: number;
  status:
    | "SUCCESS"
    | "ERROR"
    | "NOT_ENOUGH_FOUND"
    | "IN_PENDING_STATE"
    | "TIMED_OUT_OR_EXPIRED";
  message?: string;
  details?: {
    [key: string]: unknown;
  };
};

export type ProduitRequestDto = {
  produitCode?: string;
  nom: string;
  description: string;
  prix: number;
  stock: number;
  categorie: string;
  state: "ACTIVE" | "INACTIVE" | "DELETED" | "CREATE_BUT_NOT_ACTIVE";
  image: string;
};

export type ProduitResponseDto = {
  produitCode: string;
  nom: string;
  description: string;
  prix: number;
  stock: number;
  categorie: string;
  state: "ACTIVE" | "INACTIVE" | "DELETED" | "CREATE_BUT_NOT_ACTIVE";
  image: string;
};

export type RequestResultProduitResponseDto = {
  timestamp: string;
  data?: ProduitResponseDto;
  code: number;
  status:
    | "SUCCESS"
    | "ERROR"
    | "NOT_ENOUGH_FOUND"
    | "IN_PENDING_STATE"
    | "TIMED_OUT_OR_EXPIRED";
  message?: string;
  details?: {
    [key: string]: unknown;
  };
};

export type PaiementResponseDto = {
  paiementCode: string;
  montant: number;
  datePaiement: string;
  methodePaiement:
    | "CARTE_BANCAIRE"
    | "PAYPAL"
    | "VIREMENT"
    | "ESPECES"
    | "CHEQUE"
    | "MOBILE_MONEY";
  statutPaiement: "EN_ATTENTE" | "VALIDE" | "ECHOUE" | "REMBOURSE";
  commandeCode: string;
  state: "ACTIVE" | "INACTIVE" | "DELETED" | "CREATE_BUT_NOT_ACTIVE";
};

export type RequestResultPaiementResponseDto = {
  timestamp: string;
  data?: PaiementResponseDto;
  code: number;
  status:
    | "SUCCESS"
    | "ERROR"
    | "NOT_ENOUGH_FOUND"
    | "IN_PENDING_STATE"
    | "TIMED_OUT_OR_EXPIRED";
  message?: string;
  details?: {
    [key: string]: unknown;
  };
};

export type LigneCommandeRequestDto = {
  ligneCommandeCode?: string;
  commandeCode: string;
  produitCode: string;
  quantite: number;
  state: "ACTIVE" | "INACTIVE" | "DELETED" | "CREATE_BUT_NOT_ACTIVE";
};

export type LigneCommandeResponseDto = {
  ligneCommandeCode: string;
  quantite: number;
  prixUnitaire: number;
  sousTotal: number;
  commandeCode: string;
  produitCode: string;
  produitNom: string;
  state: "ACTIVE" | "INACTIVE" | "DELETED" | "CREATE_BUT_NOT_ACTIVE";
};

export type RequestResultLigneCommandeResponseDto = {
  timestamp: string;
  data?: LigneCommandeResponseDto;
  code: number;
  status:
    | "SUCCESS"
    | "ERROR"
    | "NOT_ENOUGH_FOUND"
    | "IN_PENDING_STATE"
    | "TIMED_OUT_OR_EXPIRED";
  message?: string;
  details?: {
    [key: string]: unknown;
  };
};

export type CommandeRequestDto = {
  commandeCode?: string;
  clientCode: string;
  statut?:
    | "EN_ATTENTE"
    | "CONFIRMEE"
    | "PAYEE"
    | "EN_PREPARATION"
    | "EXPEDIEE"
    | "LIVREE"
    | "ANNULEE"
    | "REMBOURSEE";
  state: "ACTIVE" | "INACTIVE" | "DELETED" | "CREATE_BUT_NOT_ACTIVE";
};

export type CommandeResponseDto = {
  commandeCode: string;
  dateCommande: string;
  statut:
    | "EN_ATTENTE"
    | "CONFIRMEE"
    | "PAYEE"
    | "EN_PREPARATION"
    | "EXPEDIEE"
    | "LIVREE"
    | "ANNULEE"
    | "REMBOURSEE";
  montantTotal: number;
  clientCode: string;
  clientNom: string;
  lignesCommande: Array<LigneCommandeResponseDto>;
  state: "ACTIVE" | "INACTIVE" | "DELETED" | "CREATE_BUT_NOT_ACTIVE";
};

export type RequestResultCommandeResponseDto = {
  timestamp: string;
  data?: CommandeResponseDto;
  code: number;
  status:
    | "SUCCESS"
    | "ERROR"
    | "NOT_ENOUGH_FOUND"
    | "IN_PENDING_STATE"
    | "TIMED_OUT_OR_EXPIRED";
  message?: string;
  details?: {
    [key: string]: unknown;
  };
};

export type ClientRequestDto = {
  clientCode?: string;
  nom: string;
  prenom: string;
  email: string;
  telephone: string;
  adresse: string;
  state: "ACTIVE" | "INACTIVE" | "DELETED" | "CREATE_BUT_NOT_ACTIVE";
  password: string;
};

export type ClientResponseDto = {
  clientCode: string;
  nom: string;
  prenom: string;
  email: string;
  telephone: string;
  adresse: string;
  state: "ACTIVE" | "INACTIVE" | "DELETED" | "CREATE_BUT_NOT_ACTIVE";
};

export type RequestResultClientResponseDto = {
  timestamp: string;
  data?: ClientResponseDto;
  code: number;
  status:
    | "SUCCESS"
    | "ERROR"
    | "NOT_ENOUGH_FOUND"
    | "IN_PENDING_STATE"
    | "TIMED_OUT_OR_EXPIRED";
  message?: string;
  details?: {
    [key: string]: unknown;
  };
};

export type AddressRequestDto = {
  addressCode: string;
  addressCountry: string;
  addressCity: string;
  addressPhoneNumber: string;
  addressEmail: string;
  addressDescription: string;
  addressAffiliationDate: string;
  addressPostalCode: string;
  addressType: "LOCATION" | "UNKNOWN";
  state: "ACTIVE" | "INACTIVE" | "DELETED" | "CREATE_BUT_NOT_ACTIVE";
  userCode: string;
};

export type UserRequestDto = {
  userCode: string;
  userNames: string;
  userPhoneNumber: string;
  userPassword: string;
  userState: "ACTIVE" | "INACTIVE" | "DELETED" | "CREATE_BUT_NOT_ACTIVE";
  roles: Array<RoleRequestDto>;
  token: string;
  userEmail: string;
  preferredCurrency: string;
  addresses: Array<AddressRequestDto>;
  image: string;
  theme: string;
};

export type RequestResultAddressResponseDto = {
  timestamp: string;
  data?: AddressResponseDto;
  code: number;
  status:
    | "SUCCESS"
    | "ERROR"
    | "NOT_ENOUGH_FOUND"
    | "IN_PENDING_STATE"
    | "TIMED_OUT_OR_EXPIRED";
  message?: string;
  details?: {
    [key: string]: unknown;
  };
};

export type GrantedAuthority = {
  authority?: string;
};

export type RequestResultUserPrincipal = {
  timestamp: string;
  data?: UserPrincipal;
  code: number;
  status:
    | "SUCCESS"
    | "ERROR"
    | "NOT_ENOUGH_FOUND"
    | "IN_PENDING_STATE"
    | "TIMED_OUT_OR_EXPIRED";
  message?: string;
};

export type UserPrincipal = {
  userCode: string;
  userFirstName: string;
  userLastName: string;
  userPhoneNumber: string;
  isActive: boolean;
  roles: Array<Role>;
  token: string;
  userEmail: string;
  imageUrl: string;
  userType: "SUPER_ADMIN" | "ADMIN" | "USER" | "CLIENT";
  userPassword: string;
  isEnabled: boolean;
  isAccountNonExpired: boolean;
  isCredentialsNonExpired: boolean;
  isAccountNonLocked: boolean;
  authorities: Array<GrantedAuthority>;
  username: string;
  password: string;
};

export type PanierRequestDto = {
  panierCode?: string;
  clientCode: string;
  state: "ACTIVE" | "INACTIVE" | "DELETED" | "CREATE_BUT_NOT_ACTIVE";
};

export type PanierResponseDto = {
  panierCode: string;
  dateCreation: string;
  clientCode: string;
  produits: Array<ProduitResponseDto>;
  state: "ACTIVE" | "INACTIVE" | "DELETED" | "CREATE_BUT_NOT_ACTIVE";
};

export type RequestResultPanierResponseDto = {
  timestamp: string;
  data?: PanierResponseDto;
  code: number;
  status:
    | "SUCCESS"
    | "ERROR"
    | "NOT_ENOUGH_FOUND"
    | "IN_PENDING_STATE"
    | "TIMED_OUT_OR_EXPIRED";
  message?: string;
  details?: {
    [key: string]: unknown;
  };
};

export type PaiementRequestDto = {
  paiementCode?: string;
  commandeCode: string;
  methodePaiement:
    | "CARTE_BANCAIRE"
    | "PAYPAL"
    | "VIREMENT"
    | "ESPECES"
    | "CHEQUE"
    | "MOBILE_MONEY";
  state: "ACTIVE" | "INACTIVE" | "DELETED" | "CREATE_BUT_NOT_ACTIVE";
};

export type RequestResultBoolean = {
  timestamp: string;
  data?: boolean;
  code: number;
  status:
    | "SUCCESS"
    | "ERROR"
    | "NOT_ENOUGH_FOUND"
    | "IN_PENDING_STATE"
    | "TIMED_OUT_OR_EXPIRED";
  message?: string;
  details?: {
    [key: string]: unknown;
  };
};

export type AppConfigRequestDto = {
  defaultCurrency: string;
  theme: string;
};

export type AppConfigResponseDto = {
  defaultCurrency: string;
};

export type RequestResultAppConfigResponseDto = {
  timestamp: string;
  data?: AppConfigResponseDto;
  code: number;
  status:
    | "SUCCESS"
    | "ERROR"
    | "NOT_ENOUGH_FOUND"
    | "IN_PENDING_STATE"
    | "TIMED_OUT_OR_EXPIRED";
  message?: string;
  details?: {
    [key: string]: unknown;
  };
};

export type UserOtpCodeDto = {
  otpCode: string;
};

export type VerifyEmailDto = {
  token: string;
};

export type RequestResultString = {
  timestamp: string;
  data?: string;
  code: number;
  status:
    | "SUCCESS"
    | "ERROR"
    | "NOT_ENOUGH_FOUND"
    | "IN_PENDING_STATE"
    | "TIMED_OUT_OR_EXPIRED";
  message?: string;
  details?: {
    [key: string]: unknown;
  };
};

export type AskTokenByEmailDto = {
  userEmail: string;
};

export type ResetPasswordDto = {
  token: string;
  password: string;
};

export type UserLoginDto = {
  login: string;
  password: string;
};

export type SuperAdminRequestDto = {
  userCode: string;
  userNames: string;
  userPhoneNumber: string;
  userPassword: string;
  userState: "ACTIVE" | "INACTIVE" | "DELETED" | "CREATE_BUT_NOT_ACTIVE";
  roles: Array<RoleRequestDto>;
  token: string;
  userEmail: string;
  preferredCurrency: string;
  addresses: Array<AddressRequestDto>;
  image: string;
  theme: string;
};

export type RequestResultUserInfoResponseDto = {
  timestamp: string;
  data?: UserInfoResponseDto;
  code: number;
  status:
    | "SUCCESS"
    | "ERROR"
    | "NOT_ENOUGH_FOUND"
    | "IN_PENDING_STATE"
    | "TIMED_OUT_OR_EXPIRED";
  message?: string;
  details?: {
    [key: string]: unknown;
  };
};

export type UserInfoResponseDto = {
  userCode: string;
  userEmail: string;
  userPhoneNumber: string;
  userNames: string;
  userLastNames: string;
  image?: Blob | File;
};

export type RequestResultListUserResponseDto = {
  timestamp: string;
  data?: Array<UserResponseDto>;
  code: number;
  status:
    | "SUCCESS"
    | "ERROR"
    | "NOT_ENOUGH_FOUND"
    | "IN_PENDING_STATE"
    | "TIMED_OUT_OR_EXPIRED";
  message?: string;
  details?: {
    [key: string]: unknown;
  };
};

export type RequestResultListRoleResponseDto = {
  timestamp: string;
  data?: Array<RoleResponseDto>;
  code: number;
  status:
    | "SUCCESS"
    | "ERROR"
    | "NOT_ENOUGH_FOUND"
    | "IN_PENDING_STATE"
    | "TIMED_OUT_OR_EXPIRED";
  message?: string;
  details?: {
    [key: string]: unknown;
  };
};

export type Pageable = {
  page?: number;
  size?: number;
  sort?: Array<string>;
};

export type PageRoleResponseDto = {
  totalPages?: number;
  totalElements?: number;
  size?: number;
  content?: Array<RoleResponseDto>;
  number?: number;
  sort?: SortObject;
  pageable?: PageableObject;
  numberOfElements?: number;
  first?: boolean;
  last?: boolean;
  empty?: boolean;
};

export type PageableObject = {
  offset?: number;
  sort?: SortObject;
  paged?: boolean;
  pageNumber?: number;
  pageSize?: number;
  unpaged?: boolean;
};

export type RequestResultPageRoleResponseDto = {
  timestamp: string;
  data?: PageRoleResponseDto;
  code: number;
  status:
    | "SUCCESS"
    | "ERROR"
    | "NOT_ENOUGH_FOUND"
    | "IN_PENDING_STATE"
    | "TIMED_OUT_OR_EXPIRED";
  message?: string;
  details?: {
    [key: string]: unknown;
  };
};

export type SortObject = {
  empty?: boolean;
  unsorted?: boolean;
  sorted?: boolean;
};

export type RequestResultListProduitResponseDto = {
  timestamp: string;
  data?: Array<ProduitResponseDto>;
  code: number;
  status:
    | "SUCCESS"
    | "ERROR"
    | "NOT_ENOUGH_FOUND"
    | "IN_PENDING_STATE"
    | "TIMED_OUT_OR_EXPIRED";
  message?: string;
  details?: {
    [key: string]: unknown;
  };
};

export type RequestResultListPaiementResponseDto = {
  timestamp: string;
  data?: Array<PaiementResponseDto>;
  code: number;
  status:
    | "SUCCESS"
    | "ERROR"
    | "NOT_ENOUGH_FOUND"
    | "IN_PENDING_STATE"
    | "TIMED_OUT_OR_EXPIRED";
  message?: string;
  details?: {
    [key: string]: unknown;
  };
};

export type RequestResultListLigneCommandeResponseDto = {
  timestamp: string;
  data?: Array<LigneCommandeResponseDto>;
  code: number;
  status:
    | "SUCCESS"
    | "ERROR"
    | "NOT_ENOUGH_FOUND"
    | "IN_PENDING_STATE"
    | "TIMED_OUT_OR_EXPIRED";
  message?: string;
  details?: {
    [key: string]: unknown;
  };
};

export type RequestResultListCommandeResponseDto = {
  timestamp: string;
  data?: Array<CommandeResponseDto>;
  code: number;
  status:
    | "SUCCESS"
    | "ERROR"
    | "NOT_ENOUGH_FOUND"
    | "IN_PENDING_STATE"
    | "TIMED_OUT_OR_EXPIRED";
  message?: string;
  details?: {
    [key: string]: unknown;
  };
};

export type RequestResultListClientResponseDto = {
  timestamp: string;
  data?: Array<ClientResponseDto>;
  code: number;
  status:
    | "SUCCESS"
    | "ERROR"
    | "NOT_ENOUGH_FOUND"
    | "IN_PENDING_STATE"
    | "TIMED_OUT_OR_EXPIRED";
  message?: string;
  details?: {
    [key: string]: unknown;
  };
};

export type RequestResultListAuthorisationResponseDto = {
  timestamp: string;
  data?: Array<AuthorisationResponseDto>;
  code: number;
  status:
    | "SUCCESS"
    | "ERROR"
    | "NOT_ENOUGH_FOUND"
    | "IN_PENDING_STATE"
    | "TIMED_OUT_OR_EXPIRED";
  message?: string;
  details?: {
    [key: string]: unknown;
  };
};

export type PageUserResponseDto = {
  totalPages?: number;
  totalElements?: number;
  size?: number;
  content?: Array<UserResponseDto>;
  number?: number;
  sort?: SortObject;
  pageable?: PageableObject;
  numberOfElements?: number;
  first?: boolean;
  last?: boolean;
  empty?: boolean;
};

export type RequestResultPageUserResponseDto = {
  timestamp: string;
  data?: PageUserResponseDto;
  code: number;
  status:
    | "SUCCESS"
    | "ERROR"
    | "NOT_ENOUGH_FOUND"
    | "IN_PENDING_STATE"
    | "TIMED_OUT_OR_EXPIRED";
  message?: string;
  details?: {
    [key: string]: unknown;
  };
};

export type RequestResultListAddressResponseDto = {
  timestamp: string;
  data?: Array<AddressResponseDto>;
  code: number;
  status:
    | "SUCCESS"
    | "ERROR"
    | "NOT_ENOUGH_FOUND"
    | "IN_PENDING_STATE"
    | "TIMED_OUT_OR_EXPIRED";
  message?: string;
  details?: {
    [key: string]: unknown;
  };
};

export type RequestResultUserPrincipalWritable = {
  timestamp: string;
  data?: UserPrincipalWritable;
  code: number;
  status:
    | "SUCCESS"
    | "ERROR"
    | "NOT_ENOUGH_FOUND"
    | "IN_PENDING_STATE"
    | "TIMED_OUT_OR_EXPIRED";
  message?: string;
};

export type UserPrincipalWritable = {
  userCode: string;
  userFirstName: string;
  userLastName: string;
  userPhoneNumber: string;
  isActive: boolean;
  roles: Array<Role>;
  token: string;
  userEmail: string;
  imageUrl: string;
  userType: "SUPER_ADMIN" | "ADMIN" | "USER" | "CLIENT";
  userPassword: string;
  isEnabled: boolean;
  isAccountNonExpired: boolean;
  isCredentialsNonExpired: boolean;
  isAccountNonLocked: boolean;
  active?: boolean;
  authorities: Array<GrantedAuthority>;
  username: string;
  password: string;
};

export type UnBlockUserData = {
  body?: never;
  path?: never;
  query: {
    userCode: string;
  };
  url: "/api/user/unblock";
};

export type UnBlockUserResponses = {
  /**
   * OK
   */
  200: RequestResultUserResponseDto;
};

export type UnBlockUserResponse =
  UnBlockUserResponses[keyof UnBlockUserResponses];

export type UpdateUserCredentialData = {
  body: UserCredentialsDto;
  headers: {
    Authorization: string;
  };
  path?: never;
  query?: never;
  url: "/api/user/myCredential";
};

export type UpdateUserCredentialResponses = {
  /**
   * OK
   */
  200: RequestResultUserResponseDto;
};

export type UpdateUserCredentialResponse =
  UpdateUserCredentialResponses[keyof UpdateUserCredentialResponses];

export type BlockUserData = {
  body?: never;
  path?: never;
  query: {
    userCode: string;
  };
  url: "/api/user/block";
};

export type BlockUserResponses = {
  /**
   * OK
   */
  200: RequestResultUserResponseDto;
};

export type BlockUserResponse = BlockUserResponses[keyof BlockUserResponses];

export type UpdateRoleData = {
  body: RoleRequestDto;
  path?: never;
  query?: never;
  url: "/api/roles/update";
};

export type UpdateRoleResponses = {
  /**
   * OK
   */
  200: RequestResultRoleResponseDto;
};

export type UpdateRoleResponse = UpdateRoleResponses[keyof UpdateRoleResponses];

export type UpdateData = {
  body: ProduitRequestDto;
  path?: never;
  query?: never;
  url: "/api/produit/update";
};

export type UpdateResponses = {
  /**
   * OK
   */
  200: RequestResultProduitResponseDto;
};

export type UpdateResponse = UpdateResponses[keyof UpdateResponses];

export type RefundData = {
  body?: never;
  path?: never;
  query: {
    paiementCode: string;
  };
  url: "/api/paiement/refund";
};

export type RefundResponses = {
  /**
   * OK
   */
  200: RequestResultPaiementResponseDto;
};

export type RefundResponse = RefundResponses[keyof RefundResponses];

export type ProcessData = {
  body?: never;
  path?: never;
  query: {
    paiementCode: string;
  };
  url: "/api/paiement/process";
};

export type ProcessResponses = {
  /**
   * OK
   */
  200: RequestResultPaiementResponseDto;
};

export type ProcessResponse = ProcessResponses[keyof ProcessResponses];

export type Update1Data = {
  body: LigneCommandeRequestDto;
  path?: never;
  query?: never;
  url: "/api/ligne-commande/update";
};

export type Update1Responses = {
  /**
   * OK
   */
  200: RequestResultLigneCommandeResponseDto;
};

export type Update1Response = Update1Responses[keyof Update1Responses];

export type Update2Data = {
  body: CommandeRequestDto;
  path?: never;
  query?: never;
  url: "/api/commande/update";
};

export type Update2Responses = {
  /**
   * OK
   */
  200: RequestResultCommandeResponseDto;
};

export type Update2Response = Update2Responses[keyof Update2Responses];

export type ConfirmData = {
  body?: never;
  path?: never;
  query: {
    commandeCode: string;
  };
  url: "/api/commande/confirm";
};

export type ConfirmResponses = {
  /**
   * OK
   */
  200: RequestResultCommandeResponseDto;
};

export type ConfirmResponse = ConfirmResponses[keyof ConfirmResponses];

export type CancelData = {
  body?: never;
  path?: never;
  query: {
    commandeCode: string;
  };
  url: "/api/commande/cancel";
};

export type CancelResponses = {
  /**
   * OK
   */
  200: RequestResultCommandeResponseDto;
};

export type CancelResponse = CancelResponses[keyof CancelResponses];

export type Update3Data = {
  body: ClientRequestDto;
  path?: never;
  query?: never;
  url: "/api/client/update";
};

export type Update3Responses = {
  /**
   * OK
   */
  200: RequestResultClientResponseDto;
};

export type Update3Response = Update3Responses[keyof Update3Responses];

export type Update4Data = {
  body: UserRequestDto;
  path?: never;
  query?: never;
  url: "/api/admin/update";
};

export type Update4Responses = {
  /**
   * OK
   */
  200: RequestResultUserResponseDto;
};

export type Update4Response = Update4Responses[keyof Update4Responses];

export type Update5Data = {
  body: AddressRequestDto;
  path: {
    addressCode: string;
  };
  query?: never;
  url: "/api/address/update/{addressCode}";
};

export type Update5Responses = {
  /**
   * OK
   */
  200: RequestResultAddressResponseDto;
};

export type Update5Response = Update5Responses[keyof Update5Responses];

export type CreateUserData = {
  body: UserRequestDto;
  path?: never;
  query?: never;
  url: "/api/user/createUser";
};

export type CreateUserResponses = {
  /**
   * OK
   */
  200: RequestResultUserResponseDto;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type ConnectedUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/user/connectedUser";
};

export type ConnectedUserResponses = {
  /**
   * OK
   */
  200: RequestResultUserPrincipal;
};

export type ConnectedUserResponse =
  ConnectedUserResponses[keyof ConnectedUserResponses];

export type CreateRoleData = {
  body: RoleRequestDto;
  path?: never;
  query?: never;
  url: "/api/roles/create";
};

export type CreateRoleResponses = {
  /**
   * OK
   */
  200: RequestResultRoleResponseDto;
};

export type CreateRoleResponse = CreateRoleResponses[keyof CreateRoleResponses];

export type CreateData = {
  body: ProduitRequestDto;
  path?: never;
  query?: never;
  url: "/api/produit/create";
};

export type CreateResponses = {
  /**
   * OK
   */
  200: RequestResultProduitResponseDto;
};

export type CreateResponse = CreateResponses[keyof CreateResponses];

export type Create1Data = {
  body: PanierRequestDto;
  path?: never;
  query?: never;
  url: "/api/panier/create";
};

export type Create1Responses = {
  /**
   * OK
   */
  200: RequestResultPanierResponseDto;
};

export type Create1Response = Create1Responses[keyof Create1Responses];

export type AddProductData = {
  body?: never;
  path?: never;
  query: {
    panierCode: string;
    produitCode: string;
    quantite: number;
  };
  url: "/api/panier/add-product";
};

export type AddProductResponses = {
  /**
   * OK
   */
  200: RequestResultPanierResponseDto;
};

export type AddProductResponse = AddProductResponses[keyof AddProductResponses];

export type Create2Data = {
  body: PaiementRequestDto;
  path?: never;
  query?: never;
  url: "/api/paiement/create";
};

export type Create2Responses = {
  /**
   * OK
   */
  200: RequestResultPaiementResponseDto;
};

export type Create2Response = Create2Responses[keyof Create2Responses];

export type Create3Data = {
  body: LigneCommandeRequestDto;
  path?: never;
  query?: never;
  url: "/api/ligne-commande/create";
};

export type Create3Responses = {
  /**
   * OK
   */
  200: RequestResultLigneCommandeResponseDto;
};

export type Create3Response = Create3Responses[keyof Create3Responses];

export type InitialisedSystemData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/initialisation/initialise";
};

export type InitialisedSystemResponses = {
  /**
   * OK
   */
  200: RequestResultBoolean;
};

export type InitialisedSystemResponse =
  InitialisedSystemResponses[keyof InitialisedSystemResponses];

export type ConfigureSystemData = {
  body: AppConfigRequestDto;
  path?: never;
  query?: never;
  url: "/api/initialisation/configure";
};

export type ConfigureSystemResponses = {
  /**
   * OK
   */
  200: RequestResultAppConfigResponseDto;
};

export type ConfigureSystemResponse =
  ConfigureSystemResponses[keyof ConfigureSystemResponses];

export type UploadFileData = {
  body?: {
    file: Blob | File;
  };
  path?: never;
  query?: never;
  url: "/api/files/upload";
};

export type UploadFileResponses = {
  /**
   * OK
   */
  200: FileData;
};

export type UploadFileResponse = UploadFileResponses[keyof UploadFileResponses];

export type Create4Data = {
  body: CommandeRequestDto;
  path?: never;
  query?: never;
  url: "/api/commande/create";
};

export type Create4Responses = {
  /**
   * OK
   */
  200: RequestResultCommandeResponseDto;
};

export type Create4Response = Create4Responses[keyof Create4Responses];

export type Create5Data = {
  body: ClientRequestDto;
  path?: never;
  query?: never;
  url: "/api/client/create";
};

export type Create5Responses = {
  /**
   * OK
   */
  200: RequestResultClientResponseDto;
};

export type Create5Response = Create5Responses[keyof Create5Responses];

export type VerifyOtpData = {
  body: UserOtpCodeDto;
  headers: {
    Authorization: string;
  };
  path?: never;
  query?: never;
  url: "/api/auth/verifyOtp";
};

export type VerifyOtpResponses = {
  /**
   * OK
   */
  200: RequestResultBoolean;
};

export type VerifyOtpResponse = VerifyOtpResponses[keyof VerifyOtpResponses];

export type VerifyEmailData = {
  body: VerifyEmailDto;
  path?: never;
  query?: never;
  url: "/api/auth/verifyEmail";
};

export type VerifyEmailResponses = {
  /**
   * OK
   */
  200: RequestResultString;
};

export type VerifyEmailResponse =
  VerifyEmailResponses[keyof VerifyEmailResponses];

export type SendTokenVerifyEmailData = {
  body: AskTokenByEmailDto;
  path?: never;
  query?: never;
  url: "/api/auth/sendTokenVerifyEmail";
};

export type SendTokenVerifyEmailResponses = {
  /**
   * OK
   */
  200: RequestResultString;
};

export type SendTokenVerifyEmailResponse =
  SendTokenVerifyEmailResponses[keyof SendTokenVerifyEmailResponses];

export type SendTokenResetPasswordData = {
  body?: never;
  path?: never;
  query: {
    userEmail: string;
  };
  url: "/api/auth/sendTokenResetPassword";
};

export type SendTokenResetPasswordResponses = {
  /**
   * OK
   */
  200: RequestResultString;
};

export type SendTokenResetPasswordResponse =
  SendTokenResetPasswordResponses[keyof SendTokenResetPasswordResponses];

export type ResetPasswordData = {
  body: ResetPasswordDto;
  path?: never;
  query?: never;
  url: "/api/auth/resetPassword";
};

export type ResetPasswordResponses = {
  /**
   * OK
   */
  200: RequestResultString;
};

export type ResetPasswordResponse =
  ResetPasswordResponses[keyof ResetPasswordResponses];

export type ResendOtpCodeData = {
  body?: never;
  path?: never;
  query: {
    login: string;
  };
  url: "/api/auth/resendOtp";
};

export type ResendOtpCodeResponses = {
  /**
   * OK
   */
  200: RequestResultString;
};

export type ResendOtpCodeResponse =
  ResendOtpCodeResponses[keyof ResendOtpCodeResponses];

export type LoginData = {
  body: UserLoginDto;
  path?: never;
  query?: never;
  url: "/api/auth/login";
};

export type LoginResponses = {
  /**
   * OK
   */
  200: RequestResultUserPrincipal;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type CreateSuperAdminData = {
  body: SuperAdminRequestDto;
  path?: never;
  query?: never;
  url: "/api/auth/createSuperAdmin";
};

export type CreateSuperAdminResponses = {
  /**
   * OK
   */
  200: RequestResultUserResponseDto;
};

export type CreateSuperAdminResponse =
  CreateSuperAdminResponses[keyof CreateSuperAdminResponses];

export type CreateAdminData = {
  body: UserRequestDto;
  path?: never;
  query?: never;
  url: "/api/admin/createAdmin";
};

export type CreateAdminResponses = {
  /**
   * OK
   */
  200: RequestResultUserResponseDto;
};

export type CreateAdminResponse =
  CreateAdminResponses[keyof CreateAdminResponses];

export type Create6Data = {
  body: AddressRequestDto;
  path?: never;
  query?: never;
  url: "/api/address/create";
};

export type Create6Responses = {
  /**
   * OK
   */
  200: RequestResultAddressResponseDto;
};

export type Create6Response = Create6Responses[keyof Create6Responses];

export type UserDetailsFromEmailOrPhoneNumberData = {
  body?: never;
  path?: never;
  query?: {
    phoneNumber?: string;
    emailAddress?: string;
  };
  url: "/api/user/userDetails";
};

export type UserDetailsFromEmailOrPhoneNumberResponses = {
  /**
   * OK
   */
  200: RequestResultUserInfoResponseDto;
};

export type UserDetailsFromEmailOrPhoneNumberResponse =
  UserDetailsFromEmailOrPhoneNumberResponses[keyof UserDetailsFromEmailOrPhoneNumberResponses];

export type FindByUserTypeData = {
  body?: never;
  path?: never;
  query: {
    userType: "SUPER_ADMIN" | "ADMIN" | "USER" | "CLIENT";
  };
  url: "/api/user/findByUserType";
};

export type FindByUserTypeResponses = {
  /**
   * OK
   */
  200: RequestResultListUserResponseDto;
};

export type FindByUserTypeResponse =
  FindByUserTypeResponses[keyof FindByUserTypeResponses];

export type FindByIdData = {
  body?: never;
  path?: never;
  query: {
    userCode: string;
  };
  url: "/api/user/findById";
};

export type FindByIdResponses = {
  /**
   * OK
   */
  200: RequestResultUserResponseDto;
};

export type FindByIdResponse = FindByIdResponses[keyof FindByIdResponses];

export type SearchData = {
  body?: never;
  path?: never;
  query: {
    search: string;
  };
  url: "/api/roles/search";
};

export type SearchResponses = {
  /**
   * OK
   */
  200: RequestResultListRoleResponseDto;
};

export type SearchResponse = SearchResponses[keyof SearchResponses];

export type SearchPaginateData = {
  body?: never;
  path?: never;
  query: {
    search: string;
    pageable?: Pageable;
  };
  url: "/api/roles/searchPaginate";
};

export type SearchPaginateResponses = {
  /**
   * OK
   */
  200: RequestResultPageRoleResponseDto;
};

export type SearchPaginateResponse =
  SearchPaginateResponses[keyof SearchPaginateResponses];

export type FindByRoleCodeData = {
  body?: never;
  path?: never;
  query: {
    roleCode: string;
  };
  url: "/api/roles/findByRoleCode";
};

export type FindByRoleCodeResponses = {
  /**
   * OK
   */
  200: RequestResultRoleResponseDto;
};

export type FindByRoleCodeResponse =
  FindByRoleCodeResponses[keyof FindByRoleCodeResponses];

export type GetByCodeData = {
  body?: never;
  path?: never;
  query: {
    produitCode: string;
  };
  url: "/api/produit/get";
};

export type GetByCodeResponses = {
  /**
   * OK
   */
  200: RequestResultProduitResponseDto;
};

export type GetByCodeResponse = GetByCodeResponses[keyof GetByCodeResponses];

export type GetByCategoryData = {
  body?: never;
  path?: never;
  query: {
    categorie: string;
  };
  url: "/api/produit/by-category";
};

export type GetByCategoryResponses = {
  /**
   * OK
   */
  200: RequestResultListProduitResponseDto;
};

export type GetByCategoryResponse =
  GetByCategoryResponses[keyof GetByCategoryResponses];

export type GetAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/produit/all";
};

export type GetAllResponses = {
  /**
   * OK
   */
  200: RequestResultListProduitResponseDto;
};

export type GetAllResponse = GetAllResponses[keyof GetAllResponses];

export type GetByClientCodeData = {
  body?: never;
  path?: never;
  query: {
    clientCode: string;
  };
  url: "/api/panier/by-client";
};

export type GetByClientCodeResponses = {
  /**
   * OK
   */
  200: RequestResultPanierResponseDto;
};

export type GetByClientCodeResponse =
  GetByClientCodeResponses[keyof GetByClientCodeResponses];

export type GetByCode1Data = {
  body?: never;
  path?: never;
  query: {
    paiementCode: string;
  };
  url: "/api/paiement/get";
};

export type GetByCode1Responses = {
  /**
   * OK
   */
  200: RequestResultPaiementResponseDto;
};

export type GetByCode1Response = GetByCode1Responses[keyof GetByCode1Responses];

export type GetByCommandeData = {
  body?: never;
  path?: never;
  query: {
    commandeCode: string;
  };
  url: "/api/paiement/by-commande";
};

export type GetByCommandeResponses = {
  /**
   * OK
   */
  200: RequestResultPaiementResponseDto;
};

export type GetByCommandeResponse =
  GetByCommandeResponses[keyof GetByCommandeResponses];

export type GetAll1Data = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/paiement/all";
};

export type GetAll1Responses = {
  /**
   * OK
   */
  200: RequestResultListPaiementResponseDto;
};

export type GetAll1Response = GetAll1Responses[keyof GetAll1Responses];

export type GetByCommande1Data = {
  body?: never;
  path?: never;
  query: {
    commandeCode: string;
  };
  url: "/api/ligne-commande/by-commande";
};

export type GetByCommande1Responses = {
  /**
   * OK
   */
  200: RequestResultListLigneCommandeResponseDto;
};

export type GetByCommande1Response =
  GetByCommande1Responses[keyof GetByCommande1Responses];

export type CheckSystemInitialisationStateData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/initialisation/checkState";
};

export type CheckSystemInitialisationStateResponses = {
  /**
   * OK
   */
  200: RequestResultBoolean;
};

export type CheckSystemInitialisationStateResponse =
  CheckSystemInitialisationStateResponses[keyof CheckSystemInitialisationStateResponses];

export type CheckSystemConfigurationData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/initialisation/checkConfiguration";
};

export type CheckSystemConfigurationResponses = {
  /**
   * OK
   */
  200: RequestResultBoolean;
};

export type CheckSystemConfigurationResponse =
  CheckSystemConfigurationResponses[keyof CheckSystemConfigurationResponses];

export type DownloadFileData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/files/download/{id}";
};

export type DownloadFileResponses = {
  /**
   * OK
   */
  200: string;
};

export type DownloadFileResponse =
  DownloadFileResponses[keyof DownloadFileResponses];

export type GetByCode2Data = {
  body?: never;
  path?: never;
  query: {
    commandeCode: string;
  };
  url: "/api/commande/get";
};

export type GetByCode2Responses = {
  /**
   * OK
   */
  200: RequestResultCommandeResponseDto;
};

export type GetByCode2Response = GetByCode2Responses[keyof GetByCode2Responses];

export type GetByClientData = {
  body?: never;
  path?: never;
  query: {
    clientCode: string;
  };
  url: "/api/commande/by-client";
};

export type GetByClientResponses = {
  /**
   * OK
   */
  200: RequestResultListCommandeResponseDto;
};

export type GetByClientResponse =
  GetByClientResponses[keyof GetByClientResponses];

export type GetAll2Data = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/commande/all";
};

export type GetAll2Responses = {
  /**
   * OK
   */
  200: RequestResultListCommandeResponseDto;
};

export type GetAll2Response = GetAll2Responses[keyof GetAll2Responses];

export type GetByCode3Data = {
  body?: never;
  path?: never;
  query: {
    clientCode: string;
  };
  url: "/api/client/get";
};

export type GetByCode3Responses = {
  /**
   * OK
   */
  200: RequestResultClientResponseDto;
};

export type GetByCode3Response = GetByCode3Responses[keyof GetByCode3Responses];

export type GetAll3Data = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/client/all";
};

export type GetAll3Responses = {
  /**
   * OK
   */
  200: RequestResultListClientResponseDto;
};

export type GetAll3Response = GetAll3Responses[keyof GetAll3Responses];

export type GetAuthorisationByGroupData = {
  body?: never;
  path?: never;
  query: {
    groupCode:
      | "MANAGE_ROLE"
      | "MANAGE_USER"
      | "MANAGE_ADDRESS"
      | "MANAGE_AUTHORISATIONS"
      | "MANAGE_SAAS_USER"
      | "NOT_SPECIFY"
      | "MANAGE_PLAYER"
      | "MANAGE_SAAS_ADMIN";
  };
  url: "/api/authorisation/getAuthorisationByGroup";
};

export type GetAuthorisationByGroupResponses = {
  /**
   * OK
   */
  200: RequestResultListAuthorisationResponseDto;
};

export type GetAuthorisationByGroupResponse =
  GetAuthorisationByGroupResponses[keyof GetAuthorisationByGroupResponses];

export type AllAuthorisationData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/authorisation/all";
};

export type AllAuthorisationResponses = {
  /**
   * OK
   */
  200: RequestResultListAuthorisationResponseDto;
};

export type AllAuthorisationResponse =
  AllAuthorisationResponses[keyof AllAuthorisationResponses];

export type AllAuthorisationsByUserTypeData = {
  body?: never;
  path?: never;
  query: {
    userCode: string;
  };
  url: "/api/authorisation/allAuthorisationsForUser";
};

export type AllAuthorisationsByUserTypeResponses = {
  /**
   * OK
   */
  200: RequestResultListAuthorisationResponseDto;
};

export type AllAuthorisationsByUserTypeResponse =
  AllAuthorisationsByUserTypeResponses[keyof AllAuthorisationsByUserTypeResponses];

export type Search1Data = {
  body?: never;
  path?: never;
  query: {
    search: string;
  };
  url: "/api/admin/searchAdmin";
};

export type Search1Responses = {
  /**
   * OK
   */
  200: RequestResultListUserResponseDto;
};

export type Search1Response = Search1Responses[keyof Search1Responses];

export type SearchPaginate1Data = {
  body?: never;
  path?: never;
  query: {
    search: string;
    pageable: Pageable;
  };
  url: "/api/admin/searchAdminPaginate";
};

export type SearchPaginate1Responses = {
  /**
   * OK
   */
  200: RequestResultPageUserResponseDto;
};

export type SearchPaginate1Response =
  SearchPaginate1Responses[keyof SearchPaginate1Responses];

export type FindById1Data = {
  body?: never;
  path?: never;
  query: {
    userCode: string;
  };
  url: "/api/admin/findById";
};

export type FindById1Responses = {
  /**
   * OK
   */
  200: RequestResultUserResponseDto;
};

export type FindById1Response = FindById1Responses[keyof FindById1Responses];

export type FindAllAdminByIsSuperAdminData = {
  body?: never;
  path?: never;
  query: {
    isSuperAdmin: boolean;
    pageable: Pageable;
  };
  url: "/api/admin/findAll";
};

export type FindAllAdminByIsSuperAdminResponses = {
  /**
   * OK
   */
  200: RequestResultPageUserResponseDto;
};

export type FindAllAdminByIsSuperAdminResponse =
  FindAllAdminByIsSuperAdminResponses[keyof FindAllAdminByIsSuperAdminResponses];

export type FindById2Data = {
  body?: never;
  path?: never;
  query: {
    addressCode: string;
  };
  url: "/api/address/findById";
};

export type FindById2Responses = {
  /**
   * OK
   */
  200: RequestResultAddressResponseDto;
};

export type FindById2Response = FindById2Responses[keyof FindById2Responses];

export type GetByPostalCodeData = {
  body?: never;
  path?: never;
  query: {
    postalCode: string;
  };
  url: "/api/address/byPostalCode";
};

export type GetByPostalCodeResponses = {
  /**
   * OK
   */
  200: RequestResultListAddressResponseDto;
};

export type GetByPostalCodeResponse =
  GetByPostalCodeResponses[keyof GetByPostalCodeResponses];

export type GetByCityData = {
  body?: never;
  path?: never;
  query: {
    city: string;
  };
  url: "/api/address/byCity";
};

export type GetByCityResponses = {
  /**
   * OK
   */
  200: RequestResultListAddressResponseDto;
};

export type GetByCityResponse = GetByCityResponses[keyof GetByCityResponses];

export type GetAll4Data = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/address/all";
};

export type GetAll4Responses = {
  /**
   * OK
   */
  200: RequestResultListAddressResponseDto;
};

export type GetAll4Response = GetAll4Responses[keyof GetAll4Responses];

export type DeleteData = {
  body?: never;
  path?: never;
  query: {
    code: string;
  };
  url: "/api/user/delete";
};

export type DeleteResponses = {
  /**
   * OK
   */
  200: RequestResultUserResponseDto;
};

export type DeleteResponse = DeleteResponses[keyof DeleteResponses];

export type DeleteRoleData = {
  body?: never;
  path?: never;
  query: {
    roleCode: string;
  };
  url: "/api/roles/delete";
};

export type DeleteRoleResponses = {
  /**
   * OK
   */
  200: RequestResultRoleResponseDto;
};

export type DeleteRoleResponse = DeleteRoleResponses[keyof DeleteRoleResponses];

export type Delete1Data = {
  body?: never;
  path?: never;
  query: {
    produitCode: string;
  };
  url: "/api/produit/delete";
};

export type Delete1Responses = {
  /**
   * OK
   */
  200: RequestResultProduitResponseDto;
};

export type Delete1Response = Delete1Responses[keyof Delete1Responses];

export type RemoveProductData = {
  body?: never;
  path?: never;
  query: {
    panierCode: string;
    produitCode: string;
  };
  url: "/api/panier/remove-product";
};

export type RemoveProductResponses = {
  /**
   * OK
   */
  200: RequestResultPanierResponseDto;
};

export type RemoveProductResponse =
  RemoveProductResponses[keyof RemoveProductResponses];

export type ClearData = {
  body?: never;
  path?: never;
  query: {
    panierCode: string;
  };
  url: "/api/panier/clear";
};

export type ClearResponses = {
  /**
   * OK
   */
  200: RequestResultPanierResponseDto;
};

export type ClearResponse = ClearResponses[keyof ClearResponses];

export type Delete2Data = {
  body?: never;
  path?: never;
  query: {
    ligneCommandeCode: string;
  };
  url: "/api/ligne-commande/delete";
};

export type Delete2Responses = {
  /**
   * OK
   */
  200: RequestResultLigneCommandeResponseDto;
};

export type Delete2Response = Delete2Responses[keyof Delete2Responses];

export type DeleteFileData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/files/{id}";
};

export type DeleteFileResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type Delete3Data = {
  body?: never;
  path?: never;
  query: {
    clientCode: string;
  };
  url: "/api/client/delete";
};

export type Delete3Responses = {
  /**
   * OK
   */
  200: RequestResultClientResponseDto;
};

export type Delete3Response = Delete3Responses[keyof Delete3Responses];

export type Delete4Data = {
  body?: never;
  path?: never;
  query: {
    addressCode: string;
  };
  url: "/api/address/delete";
};

export type Delete4Responses = {
  /**
   * OK
   */
  200: RequestResultAddressResponseDto;
};

export type Delete4Response = Delete4Responses[keyof Delete4Responses];
