/**
 * E-Commerce API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ApiResponseBoolean {
  timestamp: string;
  data: boolean;
  code: number;
  status: string;
  message?: string;
  details?: { [key: string]: any };
}
