/**
 * E-Commerce API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Product } from './product';

export interface CartItem {
  itemId: string;
  product: Product;
  quantity: number;
  subtotal?: number;
}
