/**
 * E-Commerce API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CreateSuperAdminRequest {
  userCode?: string;
  userNames?: string;
  userPhoneNumber?: string;
  userPassword?: string;
  userState?: string;
  roles?: Array<{ [key: string]: any }>;
  token?: string;
  userEmail?: string;
  preferredCurrency?: string;
  addresses?: Array<{ [key: string]: any }>;
  image?: string;
  theme?: string;
}
