/**
 * E-Commerce API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PanierProduct {
  produitCode: string;
  nom: string;
  description?: string;
  prix: number;
  stock?: number;
  categorie?: string;
  state?: string;
}
