/**
 * E-Commerce API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Product } from './product';

export interface ProductPage {
  items: Array<Product>;
  total: number;
  page: number;
  pageSize: number;
}
