/**
 * E-Commerce API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface RegisterRequest {
  nom: string;
  prenom: string;
  email: string;
  telephone: string;
  adresse: string;
  password: string;
}
